---
apiVersion: v1
kind: Service
metadata:
  name: petfriendspayment-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/petfriendspayment"
spec:
  selector:
    app:  petfriendspayment-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP